Name:           ros-indigo-ohm-rrl-perception
Version:        0.0.1
Release:        1%{?dist}
Summary:        ROS ohm_rrl_perception package

Group:          Development/Libraries
License:        MIT
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-ohm-rrl-motiondetection
Requires:       ros-indigo-ohm-rrl-perception-launch
Requires:       ros-indigo-ohm-rrl-perception-utility
BuildRequires:  ros-indigo-catkin

%description
Meta package for the perception in the robocup rescue league

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Mon Jun 04 2018 Christian Pfitzner <christian.pfitzner@th-nuernberg.de> - 0.0.1-1
- Autogenerated by Bloom

* Mon Jun 04 2018 Christian Pfitzner <christian.pfitzner@th-nuernberg.de> - 0.0.1-0
- Autogenerated by Bloom

